services:
  mago-op-database:
    image: mongo:latest
    container_name: mago-op-database
    restart: always
    ports:
      - 7017:27017
    volumes:
      - mago_op_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=orangeplanet
      - MONGO_INITDB_ROOT_PASSWORD=innovation!
    networks:
      - mago-op-network

  mago-op-database-express:
    image: mongo-express:latest
    container_name: mago-op-database-express
    restart: always
    ports:
      - 7018:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=orangeplanet
      - ME_CONFIG_MONGODB_ADMINPASSWORD=innovation!
      - ME_CONFIG_MONGODB_SERVER=mago-op-database
    depends_on:
      - mago-op-database
    command: ["sh", "-c", "sleep 10 && node app"]
    networks:
      - mago-op-network

volumes:
  mago_op_data:

networks:
  mago-op-network:
    external: true


